
// Import the functions you need from the SDKs you need
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries
// [START auth_signup_password_modular]


// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyC9yX4Pk2IPrcryAFOzwuPiI7KkdSqGssQ",
  authDomain: "shopapp-118c0.firebaseapp.com",
  projectId: "shopapp-118c0",
  storageBucket: "shopapp-118c0.appspot.com",
  messagingSenderId: "725817268798",
  appId: "1:725817268798:web:ccce66a2ba577771b60f6f"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// This snippet file was generated by processing the source file:
// ./auth-next/email.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.


